"""patients and notes

Revision ID: 461c2be277df
Revises: 2fb31339405c
Create Date: 2026-05-14 14:06:53.046228
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '461c2be277df'
down_revision: str | None = '2fb31339405c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.String(length=240), nullable=True),
    sa.Column('blood_type', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('conditions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('allergies', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('last_visit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_status'), 'patients', ['status'], unique=False)
    op.create_index(
        'ix_patients_last_name_first_name',
        'patients',
        ['last_name', 'first_name'],
        unique=False,
    )
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_patient_id'), 'notes', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_patient_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_patients_last_name_first_name', table_name='patients')
    op.drop_index(op.f('ix_patients_status'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
